### PR TITLE
Updated ACP related stuff.

### PR DESCRIPTION
**Pull request by stereomon**
- Updated App Workflow.
- Use Mini Framework as starting repository.

### CODE REVIEW

**Comment by stereomon** [comment]
At the end there is still one issue, please check and fix that.

```
 Minimal PHPMD priority of rules to fail the validation [2]:
 >
  RUN  php /Users/reneklatt/www/sdk-src/vendor/bin/phpcbf  --standard=--config='architector.php' ./src
  OUT  ERROR: the "--config=architector.php" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR2, PSR12, Squiz, Zend, SlevomatCodingStandard, GlueStreamSpecific, Spryker and SprykerStrict
  OUT
  RES  3 Command did not run successfully
The `app:ValidateProject` transition is failed, see details above.
Debug: Executing stage: build
Info: Open API file doesn't contain any errors.
Info: PHP Deprecated:  The resolvable class cache is enabled but was not generated. in /Users/reneklatt/www/bazaarvoice-test/vendor/spryker/kernel/src/Spryker/Shared/Kernel/ClassResolver/ResolvableCache/CacheReader/CacheReaderPhp.php on line 36
Info: ERROR: the "--config=architector.php" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR2, PSR12, Squiz, Zend, SlevomatCodingStandard, GlueStreamSpecific, Spryker and SprykerStrict
Info: Please fix the mentioned issues and re-run the workflow to continue.
```

**Review by pavelmaksimov25 — APPROVED** [review]

**Comment by pavelmaksimov25** [comment]
> At the end there is still one issue, please check and fix that.
> 
> ```
>  Minimal PHPMD priority of rules to fail the validation [2]:
>  >
>   RUN  php /Users/reneklatt/www/sdk-src/vendor/bin/phpcbf  --standard=--config='architector.php' ./src
>   OUT  ERROR: the "--config=architector.php" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR2, PSR12, Squiz, Zend, SlevomatCodingStandard, GlueStreamSpecific, Spryker and SprykerStrict
>   OUT
>   RES  3 Command did not run successfully
> The `app:ValidateProject` transition is failed, see details above.
> Debug: Executing stage: build
> Info: Open API file doesn't contain any errors.
> Info: PHP Deprecated:  The resolvable class cache is enabled but was not generated. in /Users/reneklatt/www/bazaarvoice-test/vendor/spryker/kernel/src/Spryker/Shared/Kernel/ClassResolver/ResolvableCache/CacheReader/CacheReaderPhp.php on line 36
> Info: ERROR: the "--config=architector.php" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR2, PSR12, Squiz, Zend, SlevomatCodingStandard, GlueStreamSpecific, Spryker and SprykerStrict
> Info: Please fix the mentioned issues and re-run the workflow to continue.
> ```
> 
> `--standard=--config='architector.php` is wrong but I don't see where that's coming from.

Would be nice to have an ability to create a bug from the github.
How I can reproduce it?

**Comment by stereomon** [comment]
You can run the app workflow and will see it in the end

**Comment by pavelmaksimov25** [comment]
> Minimal PHPMD priority of rules to fail the validation [2]:
>  >
>   RUN  php /Users/reneklatt/www/sdk-src/vendor/bin/phpcbf  --standard=--config='architector.php' ./src
>   OUT  ERROR: the "--config=architector.php" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR2, PSR12, Squiz, Zend, SlevomatCodingStandard, GlueStreamSpecific, Spryker and SprykerStrict
>   OUT
>   RES  3 Command did not run successfully
> The `app:ValidateProject` transition is failed, see details above.
> Debug: Executing stage: build
> Info: Open API file doesn't contain any errors.
> Info: PHP Deprecated:  The resolvable class cache is enabled but was not generated. in /Users/reneklatt/www/bazaarvoice-test/vendor/spryker/kernel/src/Spryker/Shared/Kernel/ClassResolver/ResolvableCache/CacheReader/CacheReaderPhp.php on line 36
> Info: ERROR: the "--config=architector.php" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR2, PSR12, Squiz, Zend, SlevomatCodingStandard, GlueStreamSpecific, Spryker and SprykerStrict
> Info: Please fix the mentioned issues and re-run the workflow to continue.

https://spryker.atlassian.net/browse/SDK-842

**Comment by pavelmaksimov25** [comment]
> You can run the app workflow and will see it in the end

https://spryker.atlassian.net/browse/SDK-842

**Pull request merged**
